### ISSUE TITLE
WEBLATE_DEBUG is true

### ISSUE THREAD

**Issue by aapeliv** [WeblateOrg/docker-compose#120]
### Describe the issue

Looking at the env, it seems `WEBLATE_DEBUG=1` is set in the main `environment` file.

At least on my reading, I was going to just follow the guide and deploy this publicly.

It might be good to add a big warning somewhere or make this `0` in the default/recommended setup?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

**Comment by nijel** [comment]
Debug mode will give user detailed error in the browser, what is usually useful for the initial setup. User will get an alert in case it is enabled (see https://docs.weblate.org/en/latest/admin/install.html#production-setup).
