### ISSUE TITLE
How to setup Gitlab integration when deploying with docker-compose?

### ISSUE THREAD

**Issue by tholu** [WeblateOrg/docker-compose#14]
Gitlab integration is available since 3.9: https://docs.weblate.org/en/weblate-3.10/vcs.html#gitlab

How do I set this up when deploying with `docker-compose`?

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/admin/install/docker.html#envvar-WEBLATE_GITLAB_USERNAME

**Comment by tholu** [comment]
Environment variables are clear so far, what about https://docs.weblate.org/en/latest/vcs.html#lab-setup ?

**Comment by nijel** [comment]
That one is done automatically as well. But currently only in the `edge` tag. It will be part of the 3.10.1 release which should happen soon (I'm waiting for last CI tests to pass before doing it).

**Comment by tholu** [comment]
Thanks for your superfast replies, will wait for 3.10.1 then!
