### ISSUE TITLE
How to debug LDAP authentication?

### ISSUE THREAD

**Issue by tholu** [WeblateOrg/docker-compose#15]
I have setup the necessary LDAP config in `docker-compose.override.yml`, however the LDAP authentication still fails with 

> This username/password combination was not found. Please try again.

 I have switched on `WEBLATE_DEBUG`, but there seems to be no way to debug where it falls exactly. Do I need to enable the LDAP authentication somehow? If so, how can I do that when deploying with `docker-compose`?

Setting `AUTHENTICATION_BACKENDS` (https://docs.weblate.org/en/weblate-3.10/admin/auth.html#ldap-auth) seems not to work in the environment file (format is unclear as well).

**Comment by nijel** [comment]
Check docs, it has some examples: https://docs.weblate.org/en/weblate-3.10/admin/install/docker.html#ldap

> This username/password combination was not found. Please try again.

This means that bind with given username and password has failed.

**Comment by tholu** [comment]
@nijel I actually used the examples and also set `WEBLATE_AUTH_LDAP_BIND_DN` and `WEBLATE_AUTH_LDAP_BIND_PASSWORD`, but I see nothing in the logs indicating what exactly has failed - username/password is 100% correct and is working with other implementation of LDAP auth. 

I'm just not sure if Weblate even tries the LDAP authentication, because it is not explicitly configured to do so.

**Comment by tholu** [comment]
Using `WEBLATE_AUTH_LDAP_BIND_DN` and  `WEBLATE_AUTH_LDAP_BIND_PASSWORD` should have been a hint to also use `WEBLATE_AUTH_LDAP_USER_SEARCH` instead of `WEBLATE_AUTH_LDAP_USER_DN_TEMPLATE `.

I configured `WEBLATE_AUTH_LDAP_USER_SEARCH` with `ou=people,dc=example,dc=com` and it works now.
