### ISSUE TITLE
 no matching manifest for linux/arm/v7 in the manifest list entries

### ISSUE THREAD

**Issue by AurelienCaille** [WeblateOrg/docker-compose#215]
### Describe the issue

Hello,

I have a 
`
no matching manifest for linux/arm/v7 in the manifest list entries
` with the docker compose up with my rpi4

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

follow [Getting started](https://github.com/WeblateOrg/docker-compose#getting-started) instructions on my rpi4

### Expected behavior

docker compose should run

**Comment by nijel** [comment]
Known issue, please see https://github.com/WeblateOrg/docker/issues/968
