### ISSUE TITLE
How to expose a local borg backup?

### ISSUE THREAD

**Issue by Apollon77** [WeblateOrg/docker-compose#31]
I installed weblate via docker-compose and it is saying I have no local backup ... ok, so I tried to add a new volume to the compose override file and tried mapping it into /weblate-local-backup ... result "Permission error".

So I read the Dockerfile and so came to the idea to do it inside the /home/weblate because here the owner is changed on docker start ... but also here I get a permission error.

So: What is the prefered way to setup a local borg backup and expose this as a volume?

Thank you

**Comment by nijel** [comment]
See also https://github.com/WeblateOrg/weblate/issues/4434#issuecomment-687070862
