### ISSUE TITLE
Unknown docker installation requirements

### ISSUE THREAD

**Issue by romanr** [WeblateOrg/docker-compose#4]
**Describe the bug**
Nowhere in the documentation there is a mention of what version of docker is required

**To Reproduce**

Install current version of Debian (stretch)

```
# apt-get install docker
# apt-get install docker-compose
# git clone https://github.com/WeblateOrg/docker-compose.git weblate-docker
# cd weblate-docker
# docker-compose up
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

```

My guess is that docker is too old version in current Debian?

**Comment by nijel** [comment]
The *current* version of Debian (buster) should have recent enough version ;-).  You can still install latest Docker engine on stretch using https://docs.docker.com/install/linux/docker-ce/debian/.

We use docker-compose 3 file format, what needs Docker engine 1.13.0+

**Comment by romanr** [comment]
Thank you for the quick response! I will try that.
(the new Weblate logo is looking a lot like retailer https://www.woolworths.com.au )
