### ISSUE TITLE
Not possible to not listen on external port 80

### ISSUE THREAD

**Issue by cedk** [WeblateOrg/docker-compose#6]
The docker-compose.override.yaml can only [extend the ports](https://docs.docker.com/compose/extends/#adding-and-overriding-configuration) values and not replace them.
So it is not possible to not make weblate listening on port 80 (without editing docker-compose.yaml) which is not convenient when we put weblate behind a proxy.
I think it will be better to leave ports empty in docker-compose.yaml and add it as example in the docker-compose.override.yaml.

**Comment by nijel** [comment]
Makes sense, can you please submit pull request with the change?

**Comment by cedk** [comment]
I do not know if you received a notification about  #7
