### ISSUE TITLE
CACHE after pull of redis 6.2.4 will not start. Complains FATAL CONFIG ERROR

### ISSUE THREAD

**Issue by ianathompson** [WeblateOrg/docker-compose#85]
**Describe the issue**
After doing the latest docker-compose pull for weblate, database and cache, the cache would not start. When reviewing the stderr output in Docker the system complains:
```
Attaching to cache_1
cache_1  |
cache_1  | *** FATAL CONFIG FILE ERROR (Redis 6.2.4) ***
cache_1  | Reading the configuration file, at line 2
cache_1  | >>> 'appendonly "yes" "redis-server"'
cache_1  | wrong number of arguments
cache_1 exited with code 1
```

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [ ] I tried to change the command to ```command: redis-server --appendonly yes``` as some other docker compose files do for redis. This still had the same error message.
- [ ] I removed the ```command: ["redis-server", "--appendonly", "yes"]``` code and then ran ```docker compose up cache --force-recreate``` and the cache image loaded.
- [ ] I logged into the cache image to see if I code run the redis-server command manually. It produced an error about it already running.
- [ ] I left the cache without the ```command: ["redis-server", "--appendonly", "yes"]``` code in the docker-compose.override.yml file
- [ ] I ran a ```docker compose up --force-recreate``` command on all of the images.
- [ ] The system ran as expected. 

Not sure if I missed a step or if something changed with 6.2.4.

**To Reproduce the issue**

docker compose pull
Pulling weblate
Pulling database
Pulling cache

**Expected behavior**
I expected the system to pull all the latest versions of the software, reload the configuration files and start up without issue.
It did not.

**Comment by nijel** [comment]
I could not reproduce this, but it might be some issue in the version you were running before and got exhibited during the upgrade. The CI tests pass with current version as well, so it's most likely some upgrading issue of the redis container...
